name: mlccd_viz
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.10
  - astropy
  - h5py
  - matplotlib
  - numpy<2
  - pyside6
  - pyqtgraph
  - superqt
  - coverage
  - pytest
  - opencv
  - libjxl=0.11.2
  - flake8
  - pre-commit
  - autopep8
  - scikit-image
  - scipy
  - pip
  - pyyaml
  - jsonschema
  - redis-py
  - watchdog
  - mysql-connector-python
  - python-dotenv
  - pyzmq
  - pip:
    - numpy<2
    - git+https://gitlab.com/lbl-anp/mlccd/mlccd_models.git
    - flake8-pyproject
    - docformatter[tomli]
    - pyinstaller
    - dmgbuild
    - pillow
