name: mlccd_viz
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.10
  - astropy
  - matplotlib
  - numpy<2
  - pyside6
  - pyqtgraph
  - superqt
  - coverage
  - pytest
  - opencv
  - flake8
  - scikit-image
  - pip
  - pyyaml
  - redis-py
  - watchdog
  - mysql-connector-python
  - python-dotenv
  - pyzmq
  - pip:
    - numpy<2
    - git+https://gitlab.com/lbl-anp/mlccd/mlccd_models.git
